create TABLE INTERNAL_ACCT_TBL (
  ID VARCHAR(32) NOT NULL,
  CCY VARCHAR(3) NOT NULL,
  BALANCE DECIMAL NOT NULL,
  STATUS varchar(20) NOT NULL,
  LAST_UPDATE_AT TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

